const products = [
    {
        productName: "Black Sport-Tek Sport-Wick United Performance Pullover Hoodie",
        description: "Stay dry and comfortable during every workout with the Sport-Tek Sport-Wick United Performance Pullover Hoodie. This hoodie is crafted with advanced moisture-wicking fabric to keep you sweat-free during intense activities. The soft, lightweight material offers flexibility while maintaining warmth. Perfect for layering or wearing on its own during cooler weather.",
        price: 42.00,
        tags: ["hoodie", "moisture-wicking", "activewear", "pullover"],
        availableSizes: ["S", "M", "L", "XL", "2X"],
        shortTitle: "Black Sport-Tek Hoodie",
        shortDescription: "Moisture-wicking pullover hoodie for active use.",
        newArrival: false,
        bestSeller: false,
    },
    {
        productName: "Black Hanes Women's Sport Cool Dri Performance Shirt",
        description: "Hanes Women's Sport Cool Dri Performance Shirt is designed with advanced moisture-wicking technology to keep you cool and comfortable. Whether you're pushing through an intense workout or enjoying outdoor activities, this shirt offers lightweight comfort and dries quickly, making it a perfect fit for your active lifestyle.",
        price: 25.00,
        tags: ["t-shirt", "moisture-wicking", "women's activewear", "cool-dri"],
        availableSizes: ["XS", "S", "M", "L", "XL"],
        shortTitle: "Hanes Women's Cool Dri Shirt",
        shortDescription: "Quick-drying, lightweight active shirt for women.",
        newArrival: true,
        bestSeller: false,
        sale: true,
    },
    {
        productName: "Black Port & Company Core Crewneck Sweatshirt",
        description: "The Black Port & Company Core Crewneck Sweatshirt offers a classic fit and feel with its soft fleece material, making it perfect for layering or wearing casually. Whether you're lounging or staying active, this sweatshirt is designed to provide warmth and comfort throughout the day.",
        price: 30.00,
        tags: ["sweatshirt", "crewneck", "casual", "layering"],
        availableSizes: ["S", "M", "L", "XL", "2X"],
        shortTitle: "Port & Company Sweatshirt",
        shortDescription: "Casual fleece crewneck sweatshirt for layering.",
        newArrival: false,
        bestSeller: true,
    }
];
